insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000000, 'Gal School', 'Charter School', 9733, 469, '89 Laredo Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000001, 'Yeshivat HaKotel', 'Language School', 1035, 57, '92 Foley Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000002, 'Magid School', 'Early Childhood Education Cent', 7782, 166, '13 Pam Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000003, 'Amit Boys School', 'Nursery School', 3970, 363, '240 Debary Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000004, 'Charter School', 1015, 924, '11 Snider Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000005, 'Yeshiva Torah', 'Boarding School', 4094, 677, '74 Christie Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000006, 'Ulpanat Bnei Akiva', 'Adult Education Center', 117, 694, '19 Ted Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000007, 'Hadarim School', 'Parochial School', 7539, 803, '88 Womack Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000008, 'Maale Gilboa', 'Art School', 8643, 836, '94 Lithgow Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000009, 'Margalit School', 'STEM School', 9102, 676, '54 Utada Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000010, 'Shalva School', 'Preschool', 1904, 247, '13 Santa Fe Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000011, 'Ulpanat Tzvia', 'Boarding School', 5920, 240, '11 Velizy Villacoublay Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000012, 'Yeshivat Beit', 'Engineering School', 4721, 83, '99 Gates Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000013, 'Jordan Valley', 'Science Academy', 4757, 829, '19 Rossellini Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000014, 'Nesher School', 'Music School', 5773, 225, '98 Rodgers Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000015, 'Avraham School', 'Parochial School', 5748, 822, '34 Lisboa Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000016, 'Ezra School', 'Religious School', 3067, 717, '42 Irving Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000017, 'Barak School', 'Private School', 7760, 350, '82 West Lafayette Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000018, 'Keshet School', 'Preschool', 6788, 595, '97 Jonny Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000019, 'Amit Siach Sod', 'Military School', 3385, 51, '83 Lenny Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000020, 'Ulpanat Tzvia', 'Continuing Education Program', 3039, 735, '42 Hannah Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000021, 'Bikurim School', 'Science Academy', 8055, 931, '30 Chi Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000022, 'Yarden School', 'Technical School', 1938, 351, '28 Cohn Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000023, 'Beeri School', 'Outdoor Education School', 9873, 92, '100 Heche Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000024, 'Otzma School', 'Summer School', 8800, 506, '97 Rothenburg Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000025, 'Amit Sderot', 'Online School', 9870, 454, '84 Vincent Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000026, 'Shefa School', 'Language School', 3379, 667, '43rd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000027, 'Shalom School', 'Continuing Education Program', 2342, 410, '94 Nanaimo Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000028, 'Maale School', 'Boarding School', 511, 798, '30 Harrison Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000029, 'Ateret School', 'Gifted and Talented School', 8433, 188, '81 Hartford Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000030, 'Yozma School', 'International School', 9871, 940, '49 Hauser Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000031, 'Yeshivat Binat', 'Parochial School', 6825, 962, '65 Bridges Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000032, 'Miri School', 'Online School', 9050, 65, '22 Lois Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000033, 'Magal School', 'Business School', 4458, 854, '40 Colleen Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000034, 'Nogah School', 'Business School', 2449, 125, '89 Oulu Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000035, 'Maale Habsor', 'Alternative School', 8518, 388, '2 Brendan Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000036, 'Yeshivat Binat', 'Gifted and Talented School', 9689, 245, '60 Bill Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000037, 'Amit Renanim', 'Community College', 8331, 830, '38 Pantoliano Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000038, 'Bnei Akiva Orot', 'Adult Education Center', 6478, 498, '545 Meyer Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000039, 'Maale Gilboa', 'Vocational School', 5845, 983, '73rd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000040, 'Torat Chaim', 'Law School', 4865, 301, '46 Debra Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000041, 'Boaz School', 'College', 7772, 521, '281 Matarazzo');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000042, 'Haroeh School', 'Business School', 9623, 766, '209 Twilley Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000043, 'Yad Harutzim', 'Music School', 1431, 564, '66 Kinski');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000044, 'Darca Makif', 'Night School', 2813, 990, '61 Stocksbridge');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000045, 'Orot Yehuda', 'Youth Center', 1500, 219, '351 Coughlan Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000046, 'Yavne School', 'Boarding School', 9608, 892, '85 Nigel Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000047, 'Amit Eilat', 'Graduate School', 15, 803, '45 Brock Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000048, 'Eitan School', 'Elementary School', 8427, 372, '18 Joaquim Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000049, 'Magen School', 'Private School', 8299, 163, '63 Ammons Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000050, 'Binah School', 'Homeschooling Program', 8342, 934, '65 Harrisburg Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000051, 'Arava School', 'Charter School', 2598, 132, '2 Winstone Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000052, 'Kiryat Yearim', 'Online School', 3130, 81, '21 Black Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000053, 'Sports Academy', 4419, 965, '15 Stevenson Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000054, 'Giora School', 'STEM School', 2327, 573, '80 High Wycombe Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000055, 'Adar School', 'Military School', 6597, 238, '43 Lauper Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000056, 'Holon School', 'Science Academy', 5392, 562, '73 Ratzenberger Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000057, 'Shavei School', 'Online School', 4923, 176, '11 Finn Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000058, 'Shavei School', 'Kindergarten', 815, 195, '201 Sundsvall Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000059, 'Magen School', 'Parochial School', 9955, 99, '54 New Delhi Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000060, 'Amit Shaked', 'Dance School', 9217, 777, '41 Deschanel Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000061, 'Itamar School', 'Adult Education Center', 7774, 268, '1 Lucien Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000062, 'Kiryat Shalom', 'After-School Program', 9305, 15, '80 Schiavelli Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000063, 'Hatzav School', 'Technical Institute', 6020, 667, '89 Rollins Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000064, 'Anafa School', 'Science Academy', 1091, 866, '13 Aberdeen Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000065, 'Elementary School', 9062, 704, '44 Jon Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000066, 'Yeshivat Shefa', 'Boarding School', 6660, 463, '971 Douglas Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000067, 'Magal School', 'Medical School', 9106, 811, '41 Oldenburg Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000068, 'Zevulun School', 'Military School', 8050, 174, '71 Manchester Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000069, 'Meytar School', 'Parochial School', 6554, 960, '40 Recife Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000070, 'Community College', 6033, 671, '11st Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000071, 'Otzma School', 'Law School', 4809, 482, '61 Nick Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000072, 'Bracha School', 'Homeschooling Program', 8081, 487, '382 Courbevoie Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000073, 'Yeshivat HaKotel', 'Special Education School', 4567, 753, '32 de Lancie Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000074, 'Magnet School', 8260, 912, '45 Arnold Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000075, 'Continuing Education Program', 3672, 818, '89 Swayze Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000076, 'Graduate School', 3381, 820, '64 Womack Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000077, 'Ron High School', 'Preschool', 3188, 323, '845 Gates Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000078, 'Menucha School', 'Bilingual School', 7123, 706, '19 Swayze Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000079, 'Bialik School', 'Summer School', 1761, 143, '65 Lodi Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000080, 'Pelech School', 'Online School', 5031, 929, '85 Sossamon Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000081, 'Migdal Oz', 'Continuing Education Program', 6340, 690, '31st Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000082, 'Ramat High School', 'Medical School', 2572, 942, '23rd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000083, 'Hadassah School', 'Private School', 5180, 502, '303 Cusack');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000084, 'Shearim School', 'Military School', 2027, 669, '52 Keeslar Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000085, 'Yedidya School', 'Nursery School', 8466, 334, '50 Billund Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000086, 'Marganit School', 'Preschool', 6327, 967, '37 Rhett Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000087, 'Drom Yehuda', 'Alternative School', 3713, 317, '1 Sorocaba Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000088, 'Kohav School', 'Gifted and Talented School', 8971, 227, '19 Kirsten Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000089, 'Sarig School', 'Adult Education Center', 9291, 118, '93 Sendai Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000090, 'Hashalom School', 'Kindergarten', 6483, 481, '79 Carrie Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000091, 'Amit Junior High', 'Continuing Education Program', 8739, 551, '62nd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000092, 'Yeshivat Shaarei', 'Public School', 7159, 190, '43 Brown Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000093, 'Betar School', 'Military School', 3142, 436, '7 Embeth Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000094, 'Oran School', 'Charter School', 5915, 588, '8 Ellicott City Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000095, 'Modi School', 'Sports Academy', 2933, 590, '8 Moody Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000096, 'Nofim School', 'Dance School', 1501, 438, '36 Guinness Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000097, 'Yeshivat Lev', 'Online School', 3191, 801, '61st Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000098, 'Yeshiva Tichonit', 'STEM School', 9439, 516, '5 Witt Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000099, 'Ben Gurion School', 'Graduate School', 1288, 367, '87 Rochester Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000100, 'Nave School', 'Art School', 6931, 175, '82 Nugent Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000101, 'Eliyahu School', 'Music School', 4817, 79, '55 Illeana Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000102, 'Lavi School', 'Online School', 3944, 807, '81 Cazale Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000103, 'Ulpanat Shalhevet', 'Nursery School', 8384, 904, '3 Jeanne Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000104, 'Amit Ashdod', 'Alternative School', 1340, 221, '27 Zurich Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000105, 'Carmel School', 'Nursery School', 7517, 514, '48 Annie Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000106, 'Hadassah School', 'Kindergarten', 6294, 434, '32 Jose Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000107, 'Kehila School', 'Law School', 7533, 939, '63 Slater Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000108, 'Nativ School', 'Special Education School', 1941, 447, '79 Ward');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000109, 'Horev School', 'Montessori School', 1774, 467, '36 Kaunas Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000110, 'Tal High School', 'Continuing Education Program', 2164, 508, '61 Grier Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000111, 'Amit Petach', 'Homeschooling Program', 5360, 178, '60 Princeton Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000112, 'Emek School', 'Preschool', 3546, 107, '68 Rhys-Davies Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000113, 'Yozma School', 'Public School', 8647, 159, '51 Holbrook Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000114, 'Amit Petach', 'Elementary School', 4500, 413, '19 Vantaa Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000115, 'Hatzav School', 'Technical Institute', 4330, 109, '89 Winter Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000116, 'Sarig School', 'Preschool', 2936, 389, '48 Toulouse Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000117, 'Sinai School', 'High School', 5122, 435, '13rd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000118, 'Noga School', 'Graduate School', 8728, 79, '56 Syracuse Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000119, 'Sadeh School', 'After-School Program', 1617, 824, '98 Budapest Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000120, 'Bnei Akiva Yeshiva', 'Adult Education Center', 7879, 408, '15 Torres Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000121, 'Yeshivat Hevron', 'After-School Program', 8568, 523, '34 Sharon Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000122, 'Yeshivat Lev', 'Charter School', 5207, 784, '12 Leonardo Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000123, 'Nogah School', 'Charter School', 2700, 973, '47 Täby Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000124, 'Gad School', 'Nursery School', 8833, 348, '102 Bale Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000125, 'Graduate School', 5295, 730, '889 Bergen Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000126, 'Bat Ami School', 'Engineering School', 5136, 605, '42 Long Island City Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000127, 'Yeshivat HaKotel', 'Sports Academy', 7821, 333, '7 Phillips Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000128, 'Yovel School', 'Technical Institute', 6884, 715, '60 Balaban Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000129, 'Nurit School', 'Science Academy', 4180, 999, '14 West Point Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000130, 'Or Torah School', 'Sports Academy', 359, 989, '56 Harnes Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000131, 'Hashalom School', 'Continuing Education Program', 3382, 954, '415 Joan Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000132, 'Miri School', 'High School', 7739, 587, '80 Vince Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000133, 'Yeshiva Meir', 'Alternative School', 4462, 572, '46 Joey Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000134, 'Sadeh School', 'University', 2660, 378, '68 Beatty Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000135, 'Bnot Rachel School', 'Private School', 220, 160, '332 Franz Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000136, 'Matityahu School', 'Parochial School', 5356, 432, '59 Byrd Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000137, 'Betar School', 'Early Childhood Education Cent', 2308, 880, '5 Jackman Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000138, 'Haroeh School', 'STEM School', 5763, 848, '454 Daryl Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000139, 'Meron School', 'Technical Institute', 6265, 853, '8 Ted Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000140, 'Darca Shomron', 'Preschool', 2033, 534, '48 Cedar Park Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000141, 'Amit Lod', 'Preschool', 8703, 510, '69 Mantova Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000142, 'Yeshivat Har', 'Bilingual School', 6259, 803, '68 Rtp Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000143, 'Etzion School', 'Technical Institute', 5685, 791, '96 Nigel Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000144, 'Binah School', 'Business School', 9831, 66, '83rd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000145, 'Migdal School', 'Technical School', 5580, 395, '44 Bruce Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000146, 'Metzudot School', 'Summer School', 5098, 50, '60 Domino Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000147, 'Horev School', 'Community College', 8002, 853, '90 Mac Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000148, 'Yavne School', 'After-School Program', 2578, 928, '92 Ricci Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000149, 'Bat Tzion', 'Montessori School', 704, 908, '42 Casey Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000150, 'Sinai School', 'Engineering School', 6503, 527, '78 Griffiths Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000151, 'Benei Akiva', 'After-School Program', 9361, 522, '786 Benoit Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000152, 'Amit Ashdod', 'Kindergarten', 9379, 600, '31 Shorter Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000153, 'Yeshivat Netiv', 'Parochial School', 1681, 777, '10 Butler Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000154, 'Cedar School', 'High School', 3383, 294, '213 Kevin Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000155, 'Karni School', 'Business School', 3861, 872, '38 Darren Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000156, 'Matan School', 'Gifted and Talented School', 5439, 375, '59 Oldman');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000157, 'Breslev School', 'Religious School', 1109, 526, '95 Pollack Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000158, 'Yeshivat Knesset', 'Public School', 1983, 740, '55 Van Damme Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000159, 'Darca Atid', 'Magnet School', 6640, 326, '241 Gladys Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000160, 'Amit Amichai', 'Outdoor Education School', 1299, 235, '34 Donovan Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000161, 'Yeshiva Meir', 'Business School', 3357, 219, '66 Herndon Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000162, 'Cohen School', 'Online School', 8570, 891, '96 Horb Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000163, 'Mitzpe School', 'Outdoor Education School', 8733, 917, '72nd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000164, 'Harel High School', 'After-School Program', 3086, 206, '81st Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000165, 'Reali School', 'Middle School', 3637, 990, '9 Ulsteinvik Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000166, 'Morasha School', 'Kindergarten', 7650, 414, '49 Antonio Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000167, 'Bergen School', 'Charter School', 232, 725, '598 Edison Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000168, 'Gimnasia School', 'International School', 354, 72, '39 Ternitz Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000169, 'Yeshivat Ahavat', 'Night School', 9980, 60, '180 Gladys Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000170, 'Jordan Valley', 'Dance School', 9594, 32, '51 Heubach Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000171, 'Maalot High School', 'Magnet School', 693, 68, '35 Cherry Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000172, 'Amit Shavei Efrayim', 'Nursery School', 9049, 164, '45 Hauer Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000173, 'Zamir School', 'University', 7968, 829, '62 Mountain View Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000174, 'Elul School', 'Art School', 6470, 725, '35 England Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000175, 'Neot Shaked', 'Middle School', 9512, 924, '55 Lindo Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000176, 'Kohav School', 'International School', 4049, 127, '77 Dar Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000177, 'Mamlachti School', 'Law School', 1464, 521, '30 Frederic Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000178, 'Bat Tzion', 'Bilingual School', 3871, 296, '934 Craven Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000179, 'Amit Bet Shemesh', 'Dance School', 6719, 507, '44 Lynn Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000180, 'Margalit School', 'Music School', 4584, 301, '382 Gord Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000181, 'Darca Shomron', 'Graduate School', 1806, 490, '69 Kiefer Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000182, 'Kohav School', 'Parochial School', 9142, 812, '72 Griffiths Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000183, 'Kohav School', 'International School', 3697, 584, '749 Foxx Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000184, 'Amit Junior High', 'Montessori School', 6756, 292, '22 Lloyd Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000185, 'Tora Veavoda', 'Gifted and Talented School', 6400, 847, '81 Ashland Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000186, 'Maayan School', 'Public School', 3749, 506, '926 Condition Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000187, 'Yeshivat Tzvia', 'Boarding School', 9974, 716, '82 Helsinki');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000188, 'Abir Yaakov School', 'Sports Academy', 9917, 883, '793 Coughlan Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000189, 'Maale Efrayim', 'Gifted and Talented School', 5328, 977, '96 Caan Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000190, 'Amit Tzfat', 'Special Education School', 9543, 801, '710 Teng Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000191, 'Tichon Hadash', 'Outdoor Education School', 8121, 74, '59 Chloe Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000192, 'Mitzpe School', 'After-School Program', 1335, 967, '82 Berenger Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000193, 'Yeshivat Mekor', 'Charter School', 5741, 408, '19 Portman Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000194, 'Zamir School', 'Medical School', 8457, 129, '16 Hackman Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000195, 'Darca Ofek', 'Religious School', 2753, 269, '70 Plowright Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000196, 'Adult Education Center', 6893, 67, '39 Jackson Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000197, 'Almog School', 'Middle School', 6160, 442, '202 Rothenburg Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000198, 'Hofit School', 'High School', 8994, 103, '33 Badalucco Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000199, 'Harel School', 'Night School', 9340, 342, '36 Sevigny Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000200, 'Cohen School', 'Nursery School', 351, 78, '98 Unger Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000201, 'Drom Yehuda', 'Nursery School', 6875, 513, '52nd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000202, 'Ulpanat Dorot', 'Sports Academy', 106, 393, '28 Grapevine Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000203, 'Kiryat Shalom', 'Charter School', 9854, 522, '39 Wayne Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000204, 'Degania School', 'Private School', 2503, 512, '41 Schwarzenegger');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000205, 'Medical School', 8094, 964, '73 Meg Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000206, 'Yeshivat Shaarei', 'Dance School', 7379, 84, '23 Makowicz Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000207, 'Ramat High School', 'Homeschooling Program', 5874, 911, '81 Dean Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000208, 'Shavei School', 'Preschool', 4695, 969, '69 Camp Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000209, 'Herzog High School', 'Dance School', 5793, 558, '18 Kirshner');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000210, 'Abir Yaakov School', 'Art School', 9330, 628, '9 Lin Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000211, 'Maale Gilboa', 'Public School', 8465, 900, '22 Crow Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000212, 'Kehila School', 'Continuing Education Program', 8714, 887, '77 Herzogenrath');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000213, 'Yeshivat Tzvia', 'STEM School', 2168, 732, '16 Ribisi Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000214, 'Chen School', 'Engineering School', 610, 628, '80 Kylie Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000215, 'Ulpanat Amana', 'Youth Center', 4521, 581, '53rd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000216, 'Amit Siach Sod', 'Parochial School', 9284, 567, '49 Dreyfuss Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000217, 'Yeshivat Aderet', 'Kindergarten', 3555, 956, '17 Elkins Park Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000218, 'Yeshivat Yerushalayim', 'Parochial School', 1466, 268, '32nd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000219, 'Zevulun School', 'College', 1396, 448, '432 Oldman Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000220, 'Yeshivat Haroeh', 'International School', 1757, 186, '13 Mann Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000221, 'Boaz School', 'Youth Center', 3324, 455, '474 Holly Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000222, 'Kohav School', 'Parochial School', 4795, 577, '3 Klein Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000223, 'Ulpanat Hadar', 'Bilingual School', 4545, 407, '36 Zafferana Etnea Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000224, 'Madregot School', 'Special Education School', 2111, 537, '63rd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000225, 'Yeshivat Hevron', 'Preschool', 5441, 141, '40 Rockwell Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000226, 'Baruch School', 'Technical School', 8261, 29, '95 Ellicott City Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000227, 'Erez School', 'Sports Academy', 1971, 857, '20 Ruiz Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000228, 'Tora Veavoda', 'Middle School', 6015, 167, '63 L''union Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000229, 'Shorashim School', 'Summer School', 5769, 456, '766 Antonio Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000230, 'Migdal Oz', 'Bilingual School', 9433, 521, '76 Ingelheim Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000231, 'Amit Siach Sod', 'Vocational School', 4151, 858, '11 Brolin Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000232, 'Elitzur School', 'Special Education School', 9917, 762, '301 Rip Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000233, 'Yeshivat Neve', 'Early Childhood Education Cent', 1518, 92, '85 Augst');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000234, 'Horev Yeshiva', 'Law School', 4380, 784, '19 Murray Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000235, 'Oran School', 'Language School', 7340, 982, '88 Beatty Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000236, 'Ulpanat Bnei Akiva', 'Youth Center', 1927, 898, '2 Ferrell Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000237, 'Amit Modi\''in', 'Technical School', 9636, 574, '44 Zappacosta Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000238, 'Dorot School', 'Art School', 6923, 505, '976 Fonda Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000239, 'Betar School', 'Business School', 4843, 618, '19 Foley Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000240, 'Shomria School', 'Adult Education Center', 5737, 132, '961 Teng');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000241, 'Yeshivat Aderet', 'Early Childhood Education Cent', 9307, 934, '81 Woking Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000242, 'Yeshivat Nachshon', 'University', 8507, 871, '1 Greg Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000243, 'Harel School', 'Business School', 1647, 253, '18 Brody Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000244, 'Yeshiva Torah', 'Night School', 4333, 398, '2 Morton Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000245, '''Ortam School'')', 'Technical Institute', 4569, 543, '224 Baldwin Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000246, 'Einav School', 'Kindergarten', 9571, 34, '35 Lisa Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000247, 'Jerusalem School', 'Adult Education Center', 5409, 734, '466 Willem Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000248, 'Tzur School', 'Kindergarten', 5208, 128, '121 Long Island City Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000249, 'Ulpanat Shalhevet', 'STEM School', 2749, 853, '94 Knight Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000250, 'Eshkolot School', 'Middle School', 2208, 213, '78 Kenneth Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000251, 'Tichon Ramah', 'Gifted and Talented School', 6720, 910, '8 Lipnicki Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000252, 'University', 4008, 497, '61 Molly Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000253, 'Yad Harutzim', 'College', 171, 143, '68 Bryson Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000254, 'Einav School', 'Public School', 6178, 253, '10 Venice Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000255, 'Dor School', 'Art School', 9962, 32, '59 Buenos Aires Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000256, 'Yeshiva Bnei Akiva', 'College', 6658, 385, '78 Sander Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000257, 'Maale Gilboa', 'International School', 7324, 471, '70 Reiner Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000258, 'Rappaport School', 'Dance School', 7972, 84, '45 Sampson Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000259, 'Amit Bnei Brak', 'Youth Center', 8504, 820, '100 Pantoliano Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000260, 'Tiferet School', 'Elementary School', 5776, 748, '83 Bolzano Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000261, 'Shalva School', 'Sports Academy', 3542, 706, '150 Cartlidge Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000262, 'Tichon Ramah', 'Music School', 1529, 499, '52 Stuart Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000263, 'Binah School', 'International School', 4244, 630, '49 Pusan-city Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000264, 'Eden School', 'Homeschooling Program', 4922, 247, '65 Elizondo');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000265, 'Levona School', 'Religious School', 3772, 668, '72nd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000266, 'Miriam School', 'Parochial School', 2825, 868, '37 Garry Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000267, 'Yeshivat Yerushalayim', 'Special Education School', 3433, 806, '99 Münster Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000268, 'Tichon Ramah', 'Homeschooling Program', 4305, 924, '44 Allan Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000269, 'Hazor School', 'Kindergarten', 7572, 531, '69 Prinze Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000270, 'Yeshivat Haroeh', 'Montessori School', 7174, 748, '53 Pleasence Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000271, 'Bnei Akiva Amana', 'Military School', 368, 806, '47 De Niro Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000272, 'Yeshiva Tichonit', 'Charter School', 9419, 279, '7 Russell Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000273, 'Amit Sderot', 'Religious School', 1888, 562, '89 South Jordan Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000274, 'Yeshivat Shaarei', 'Sports Academy', 749, 335, '79 Art Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000275, 'Ulpanat Horev', 'STEM School', 2119, 210, '98 Vertical Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000276, 'Yeshivat Chaim', 'Graduate School', 503, 696, '66 Anières');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000277, 'Shomria School', 'Law School', 6721, 845, '60 Barueri Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000278, 'Amit Renanim', 'Summer School', 4667, 270, '71st Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000279, 'Elitzur School', 'Preschool', 7886, 31, '9 Taylor Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000280, 'Matan School', 'Art School', 553, 982, '56 Stuart Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000281, 'Neve Shalom', 'Science Academy', 3938, 298, '74 Isaak Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000282, 'Yeshivat Sinai', 'Technical School', 35, 26, '98 Zevon Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000283, 'Maccabim School', 'After-School Program', 6458, 863, '11st Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000284, 'College', 3781, 254, '76 Gil Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000285, 'Himmelfarb School', 'Bilingual School', 2885, 919, '15 Liotta Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000286, 'Shalva School', 'Parochial School', 223, 17, '24 Stiller Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000287, 'Amram School', 'Sports Academy', 1783, 996, '25 Cledus Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000288, 'Lachish School', 'Bilingual School', 8747, 176, '133 Dean Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000289, 'Meytar School', 'Art School', 9118, 990, '61 Walnut Creek Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000290, 'Mikdash School', 'Online School', 9272, 837, '15 Clarence Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000291, 'Negev School', 'Early Childhood Education Cent', 1384, 926, '44 Elisabeth Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000292, 'Parochial School', 7309, 896, '21 Snow Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000293, 'Sinai School', 'International School', 7278, 260, '45 Ternitz Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000294, 'Amirim School', 'After-School Program', 6577, 574, '36 John Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000295, 'Reut School', 'Kindergarten', 4065, 63, '75 Woodard');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000296, 'Benei Akiva', 'Parochial School', 1657, 12, '99 Whitwam Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000297, 'Or Avner School', 'Engineering School', 1654, 638, '80 Blackwell Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000298, 'Bracha School', 'Continuing Education Program', 6489, 344, '62nd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000299, 'Maale School', 'Language School', 8954, 407, '68 Rita Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000300, 'Carmel School', 'College', 4800, 452, '20 München Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000301, 'Morasha School', 'Private School', 4406, 463, '22 Nelly Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000302, 'Itamar School', 'College', 646, 3, '99 Lynne Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000303, 'Ofra School', 'Outdoor Education School', 2276, 741, '40 Tia Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000304, 'Bracha School', 'Bilingual School', 8824, 312, '52 Minneapolis');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000305, 'Amit Ashdod', 'Bilingual School', 4051, 326, '3 Adamstown Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000306, 'Yeshivat Shalhevet', 'Technical School', 400, 932, '50 Tyler Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000307, 'Levona School', 'Preschool', 1584, 434, '1 Grapevine Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000308, 'Hamagen School', 'Business School', 917, 122, '23 Den Haag Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000309, 'Kolech School', 'Community College', 4930, 404, '22nd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000310, 'Keshet School', 'Continuing Education Program', 9684, 572, '61st Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000311, 'Lev HaTorah', 'Gifted and Talented School', 6780, 532, '643 Bruxelles Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000312, 'Hadarim School', 'Adult Education Center', 2537, 919, '69 Madonna Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000313, 'Ulpanat Hadar', 'Gifted and Talented School', 7892, 60, '21 Chilton Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000314, 'Kiryat Noar', 'Special Education School', 492, 723, '21 Omar Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000315, 'Amit Kfar Batya', 'Preschool', 3235, 598, '355 Lexington Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000316, 'Amirim School', 'STEM School', 4741, 391, '17 Katrin Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000317, 'Benei Akiva', 'Dance School', 5158, 208, '1 Vinton Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000318, 'Yerucham School', 'Charter School', 4754, 340, '46 Darren Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000319, 'Golan School', 'Online School', 3596, 167, '24 McCormack Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000320, 'Yeshivat Har', 'Language School', 9630, 221, '79 Nikki Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000321, 'Dor School', 'Engineering School', 4084, 445, '34 Rick Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000322, 'Summer School', 8750, 860, '91 Tomlin Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000323, 'Givati School', 'Online School', 5163, 259, '305 Hagar Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000324, 'Neve Shalom', 'Sports Academy', 4041, 622, '25 Clark Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000325, 'Meytar School', 'Outdoor Education School', 1892, 245, '463 Portland Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000326, 'Maale School', 'Preschool', 8938, 636, '71 Ohita Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000327, 'Yeshiva Darca', 'Engineering School', 806, 153, '45 Kurt Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000328, 'Hayovel School', 'Medical School', 2874, 390, '15 Sheryl Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000329, 'Pelech School', 'Online School', 516, 626, '65 Molly Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000330, 'Ulpanat Amana', 'Montessori School', 8690, 209, '45 France Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000331, 'Lavi School', 'Art School', 1569, 365, '13 Todd Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000332, 'Sadeh School', 'Law School', 1814, 997, '29 Pierce Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000333, 'Bnei Akiva Yeshiva', 'Online School', 3819, 473, '38 Will Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000334, 'Mikdash School', 'Magnet School', 1322, 638, '926 Peet Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000335, 'Misgav School', 'Dance School', 9241, 927, '30 Stanley Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000336, 'Maale School', 'Medical School', 2120, 974, '95 Jennifer Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000337, 'Abir Yaakov School', 'Language School', 3563, 942, '866 Dietikon');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000338, 'Kohav School', 'University', 3482, 406, '566 Sheryl Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000339, 'Kohav School', 'STEM School', 5332, 471, '61 Heubach Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000340, 'David School', 'Engineering School', 9980, 180, '63rd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000341, 'Neve Shalom', 'Religious School', 1270, 793, '11 Katie Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000342, 'Kalanit School', 'Middle School', 8417, 402, '51 Cassel Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000343, 'Yovel School', 'Community College', 635, 483, '21 Palo Alto');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000344, 'Ben David', 'Night School', 2866, 58, '97 Ft. Leavenworth');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000345, 'Givati School', 'Kindergarten', 8638, 860, '81st Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000346, 'Shavei School', 'Adult Education Center', 1069, 877, '962 Stewart Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000347, 'Haroeh School', 'Alternative School', 7630, 992, '99 Kathy Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000348, 'Eitan School', 'Kindergarten', 9733, 680, '12 Salisbury Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000349, 'Kohav School', 'Preschool', 9246, 349, '74 Horace Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000350, 'Amit Modi\''in', 'Vocational School', 457, 881, '53rd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000351, 'Gur School', 'Art School', 307, 530, '24 Dunn');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000352, 'Shalva School', 'Summer School', 3499, 964, '4 Holly Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000353, 'Yeshivat Netiv', 'Community College', 5393, 448, '998 Neeson Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000354, 'David School', 'Montessori School', 6381, 800, '34 Green Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000355, 'Merav School', 'Technical School', 4671, 949, '72 Griffin Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000356, 'Ulpanat Horev', 'Bilingual School', 5130, 162, '13rd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000357, 'Nachal School', 'Summer School', 3825, 648, '11 Joshua Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000358, 'Nachshon School', 'Private School', 8544, 866, '80 Popper Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000359, 'Maccabim School', 'Boarding School', 191, 408, '92 Frankie Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000360, 'Amit Siach Sod', 'Sports Academy', 5475, 91, '2 Wahlberg Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000361, 'Or Torah School', 'Religious School', 2848, 566, '80 Daryle Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000362, 'Hashalom School', 'Vocational School', 7873, 199, '41 Negbaur Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000363, 'Marganit School', 'Dance School', 129, 307, '19 Highlands Ranch Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000364, 'Chorev High School', 'Bilingual School', 1781, 350, '25 Horsham Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000365, 'Yeshivat Nachshon', 'University', 8682, 455, '23rd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000366, 'Gal School', 'Adult Education Center', 2647, 798, '89 Eileen Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000367, 'Yeshivat Yerushalayim', 'Continuing Education Program', 326, 523, '81 Rispoli Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000368, 'Amit Modi\''in', 'Law School', 4320, 894, '529 Chesnutt Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000369, 'Hillel School', 'After-School Program', 8821, 907, '806 Sarsgaard Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000370, 'Charter School', 8517, 303, '72 Savage Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000371, 'Mikveh Shalom', 'Youth Center', 6897, 416, '1 Visnjic Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000372, 'Idan School', 'Bilingual School', 9193, 382, '99 Hamilton Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000373, 'Shachar High', 'Charter School', 5371, 340, '5 Meryl Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000374, 'Nave Yeshiva', 'Homeschooling Program', 6846, 478, '92 Rebecca Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000375, 'Otzma School', 'Technical Institute', 3083, 168, '785 Kate Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000376, 'Dagim School', 'Alternative School', 7055, 177, '15 Horizon Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000377, 'Oran School', 'International School', 7798, 221, '34 Monterrey Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000378, 'Noam Bnei Akiva', 'After-School Program', 803, 49, '44 Lucien Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000379, 'Lavi School', 'Outdoor Education School', 1929, 797, '56 Gerald Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000380, 'Cedar School', 'Medical School', 3009, 864, '267 Lake Bluff Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000381, 'Nili School', 'Religious School', 6791, 679, '29 El Paso Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000382, 'Elitzur School', 'Dance School', 2618, 952, '73 Miles Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000383, 'Horev Yeshiva', 'Preschool', 2005, 413, '59 Lisbon Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000384, 'Zevulun School', 'Gifted and Talented School', 9549, 81, '98 Farrell Blvd');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000385, 'Yeshivat Neve', 'Special Education School', 5619, 864, '72 Lightfoot Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000386, 'Himmelfarb School', 'Language School', 4680, 524, '58 The Woodlands Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000387, 'Amit Netanya', 'Technical School', 6226, 598, '86 Francis Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000388, 'Chen School', 'University', 7706, 627, '13 Johnette');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000389, 'Amit Boys School', 'College', 2274, 284, '58 Natal');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000390, 'Hadassim School', 'Business School', 1344, 330, '41 Shirley Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000391, 'Mamlachti School', 'Graduate School', 4695, 263, '23rd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000392, 'Yeshivat Neve', 'Magnet School', 9813, 357, '64 Senior Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000393, 'Drom Yehuda', 'STEM School', 1844, 134, '23rd Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000394, 'Ayala School', 'Military School', 5571, 893, '15 Bogguss Ave');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000395, 'Golomb School', 'Preschool', 9609, 248, '77 Gallagher Drive');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000396, 'Tzofim School', 'College', 3825, 95, '97 Drive Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000397, 'Carmel School', 'Middle School', 2472, 102, '229 Feuerstein Street');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000398, 'Dagim School', 'Graduate School', 3143, 556, '61 Cape town Road');

insert into SYS.ACADEMIC_INSTITUTION (INSTITUTIONID, NAME, KIND, NUMOFSTUDENTS, NUMOFTEACHERS, ADDRESS)
values (1000000399, 'Zeev School', 'International School', 5454, 617, '69 Frakes Ave');

commit;
